### ISSUE TITLE
Improve the books cards

### ISSUE THREAD

**Issue by akanksha984** [NageshMandal/Engineering-Notes-Website#910]
![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/97845909/bdf9f676-951e-43df-89fe-76faa4321b0b)

**Comment by ParthMadhvani2** [comment]
hey, improved the book card issue So please assign this issue to me. I am a GSSOC'23 contributor and had solved this problem. So please assign it to me under the GSSOC'23 label.

**Comment by akanksha984** [comment]
@NageshMandal  please check https://github.com/NageshMandal/Engineering-Notes-Website/pull/908 both the issues has been resolved in this

**Comment by ParthMadhvani2** [comment]
No, i have not resolved this issue #908
But would resolve it if you accept this request. Please merge this as I am
GSSOC'23 contributor.

**Comment by akanksha984** [comment]
@ParthMadhvani2 I have made it already.. and I was assigned this issue and working on it and completed it..

**Comment by ParthMadhvani2** [comment]
ok
